### ISSUE TITLE
Virginia Woolf misspelled in About text

### ISSUE THREAD

**Issue by zygoballus** [standardebooks/virginia-woolf_orlando#4]
The About text for this project says: "Epub source for the Standard Ebooks edition of Orlando, by Virinia Woolf".

Also, there are hundreds of grammatical changes in this edition compared with the original 1928 edition. This edition seems to be based on the 1963 Australian reprint by Penguin Books. The large number of changes make me wonder if this version is actually public domain or not.

**Comment by acabal** [comment]
Thanks, that typo should be fixed.

The transcription is from Faded Page and they transcribed the copyright page as

````
First published 1928

Published in Penguin Books 1942

Reprinted 1963
````

Therefore it's US-PD. In general, changes to punctuation do not grant a new copyright. If you think there are more complex changes in this edition compared to 1928, please share some specific examples.

**Comment by zygoballus** [comment]
@acabal - Honestly, I'm not sure if the changes are editorial or just a bad transcription. If we look at the first couple pages:
* of his sex -> about his sex
* on a cocoanut -> of a coconut
* winter or summer -> winter and summer
* of a vast coat of arms -> on a vast coat of arms
* reach what ever seat -> reach whatever seat
* rhapsodise -> rhapsodize

I'm comparing against the 1928 New York edition. I was going to proofread the whole book, but there are so many differences I thought maybe it was because it was a different edition. Unfortunately, I don't have access to the Penguin Books edition (since they sued Google and Internet Archive), so I can't tell.

**Comment by zygoballus** [comment]
Interestingly, the 1928 London edition has "winter and summer" and "reach whatever seat", so those two changes might be specific to the 1928 New York edition. I suppose the changes aren't substantial enough to warrant copyright protection, but it's interesting there are so many differences between these editions, like multiple differences per page.

**Comment by acabal** [comment]
We update some spelling as part of our process, like `coconut`. `rhapsodise` vs `rhapsodize` is UK vs American spelling so whichever edition you're looking at was for a different market than the transcription edition. As for the rest, you can check the page scans we proofed against here: https://archive.org/details/dli.ernet.524751

**Comment by acabal** [comment]
It is extremely common for there to be a huge number of differences between editions of even famous books. Editors did whatever they wanted and nobody really cared, not even the authors in most cases. This is why the concept of the "author's one true edition" is not a good way to understand books published before 1950ish, which is when US universities began to make it fashionable to put every comma under a microscope.
