### ISSUE TITLE
Transcription errors

### ISSUE THREAD

**Issue by zygoballus** [standardebooks/virginia-woolf_orlando#6]
Thanks for the quick fixes! This inspired me to give the Preface a closer proofread. Here are some more transcription errors:
Lord Macaulay -> Lord Macauley
Walter Pater,—to name -> Walter Pater⁠—to name
Mr. Sydney-Turner’s -> Mr. Sydney Turner’s
Desmond Maccarthy -> Desmond MacCarthy
most inspiriting of critics -> most inspiring of critics

**Comment by acabal** [comment]
Thanks, I have accepted some of these. 

In the future, it would be helpful if you would list the typo first, then its correction following. The other way around is confusing. Thanks!
